# Generated by Django 5.1.7 on 2025-04-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='first_release_year',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='no_of_albumns_released',
            field=models.IntegerField(null=True),
        ),
    ]
