# Generated by Django 5.1.7 on 2025-03-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_customuser_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
