# Generated by Django 5.1.7 on 2025-03-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_artist_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="address",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
