# Generated by Django 5.1.7 on 2025-04-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='artist_id',
            new_name='artist',
        ),
    ]
