# Generated by Django 5.1.7 on 2025-03-20 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250320_0423'),
    ]

    operations = [
    ]
