# Generated by Django 5.1.7 on 2025-03-20 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250320_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='artist_id',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='albumn_name',
            new_name='album_name',
        ),
        migrations.DeleteModel(
            name='ArtistMusic',
        ),
        migrations.AddField(
            model_name='music',
            name='artist_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.artist'),
            preserve_default=False,
        ),
    ]
