# Generated by Django 5.1.7 on 2025-03-20 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250320_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='artist_id',
        ),
        migrations.DeleteModel(
            name='ArtistMusic',
        ),
        migrations.AddField(
            model_name='music',
            name='artist_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music', to='core.artist'),
        ),
    ]
