# Generated by Django 5.1.7 on 2025-03-20 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_music_artist_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist_id',
            field=models.ForeignKey(db_column='artist_id', on_delete=django.db.models.deletion.CASCADE, to='core.artist'),
        ),
    ]
