# Generated by Django 5.1.7 on 2025-03-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_music_artist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='album_name',
            field=models.CharField(db_column='albumn_name', max_length=255),
        ),
    ]
