# Generated by Django 5.1.7 on 2025-03-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_music_album_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='album_name',
        ),
        migrations.AddField(
            model_name='music',
            name='albumn_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
